# Generated by Django 5.0.6 on 2024-06-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantityBuy',
        ),
    ]
