# Generated by Django 5.0.6 on 2024-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_quantitybuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_per_item', models.FloatField(default=0)),
                ('total_sales', models.FloatField(default=0)),
            ],
        ),
    ]
