# Generated by Django 5.0.6 on 2024-06-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_totalsales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantityBuyPerItem',
            field=models.BigIntegerField(default=0),
        ),
    ]
