# Generated by Django 5.0.6 on 2024-06-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_category_id_alter_product_id_alter_supplier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalsales',
            name='sales_per_week',
            field=models.FloatField(default=0),
        ),
    ]
