# Generated by Django 5.0.6 on 2024-06-13 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_totalsales_sales_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sales_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='totalsales',
            name='sales_per_week',
        ),
    ]
