# Generated by Django 5.0.6 on 2024-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_dailysales_remove_totalsales_sales_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='background_profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='customer_profiles/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='customer_profiles/'),
        ),
    ]
