# Generated by Django 5.0.6 on 2024-06-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
