# Generated by Django 5.0.6 on 2024-07-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
