# Generated by Django 5.0.6 on 2024-07-06 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_dailysales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
